version: '3'
services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    networks:
      - postgres
    ports:
      - '5432:5432'
    # volumes:
    # - /data/postgres:/data/postgres
    volumes:
      - /_data/postgresql:/var/lib/postgresql
      - /_data/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:6.18
    container_name: pgadmin
    networks:
      - postgres
    ports:
      - '8080:80'
    volumes:
      - /_data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  nestjs-api:
    build:
      context: .
      target: install-dependencies
    command: npm run start:dev
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - postgres
    networks:
      - postgres
    links:
      - 'postgres:postgres'
    container_name: nestjs
  # migration:
  #   build:
  #     context: .
  #   command:
  #     ['./wait-for-it/wait-for-it.sh', '5432', '--', 'npm', 'run', 'migrate']

networks:
  postgres:
    driver: bridge
